openapi: 3.1.0
info:
  title: Common Schema
  description: 공통 스키마를 정의하는 문서
  version: 0.0.1
  contact:
    name: Team Ourfit
    email: teamourfit@gmail.com
servers:
  - url: https://dev.not-available-yet.com
    description: Development
  - url: https://not-available-yet.com
    description: Production

components:
  schemas:
    BaseResponse:
      description: "표준 응답"
      type: object
      properties:
        message:
          type: string
          example: "OK"
          description: "HTTP 상태 메세지"
        data:
          type: object
          description: "응답 데이터"

    PageResponse:
      description: "페이지네이션 응답"
      allOf:
        - $ref: "#/components/schemas/BaseResponse"
        - type: object
          properties:
            data:
              type: object
              description: "페이지네이션 데이터"
              properties:
                content:
                  type: array
                  description: "응답 데이터 목록"
                pageable:
                  type: object
                  description: "페이지네이션 관련 정보"
                  properties:
                    pageNumber:
                      type: integer
                      example: 1
                      description: "현재 페이지 번호 (1부터 시작)"
                    pageSize:
                      type: integer
                      example: 10
                      description: "한 페이지당 데이터 개수"
                    sort:
                      type: object
                      description: "정렬 정보"
                      properties:
                        empty:
                          type: boolean
                          description: "정렬 조건이 비어 있는지 여부"
                        sorted:
                          type: boolean
                          description: "정렬이 적용되었는지 여부"
                        unsorted:
                          type: boolean
                          description: "정렬이 적용되지 않았는지 여부"
                totalPages:
                  type: integer
                  example: 5
                  description: "전체 페이지 개수"
                totalElements:
                  type: integer
                  example: 50
                  description: "전체 데이터 개수"
                last:
                  type: boolean
                  example: false
                  description: "현재 페이지가 마지막 페이지인지 여부"
                first:
                  type: boolean
                  example: true
                  description: "현재 페이지가 첫 페이지인지 여부"
                size:
                  type: integer
                  example: 10
                  description: "페이지 크기 (한 페이지당 요소 개수)"
                number:
                  type: integer
                  example: 1
                  description: "현재 페이지 번호 (1부터 시작)"
                numberOfElements:
                  type: integer
                  example: 10
                  description: "현재 페이지에서 반환된 요소 개수"
                empty:
                  type: boolean
                  example: false
                  description: "현재 페이지가 비어 있는지 여부"

    ErrorResponse:
      description: "표준 오류 응답"
      type: object
      properties:
        message:
          type: string
          example: "Http Status Message"
          description: "HTTP 상태 메세지"
        data:
          $ref: "#/components/schemas/ErrorData"

    ErrorData:
      description: "오류 상세 정보"
      type: object
      properties:
        message:
          type: string
          example: "Error Details"
          description: "오류에 대한 설명"
        code:
          type: integer
          example: 500001
          description: "디버깅 등 내부 관리용 코드(6자리 숫자)"
