openapi: 3.0.0
info:
  title: Auth API
  description: 인증 API
  version: 0.0.1
servers:
  - url: https://api.ourfit.life
paths:
  /v1/oauth2/{provider}/redirect:
    get:
      summary: OAuth2 Callback API
      description: |
        OAuth2 인증 과정의 리다이렉트를 처리하는 API
        1. 사용자가 OAuth2 인증 화면에서 로그인하면, OAuth2 서비스 제공자는 인가 코드를 발급하고, 이 엔드포인트로 리다이렉트된다.
        2. 이 API는 인가 코드로 사용자를 인증하고, 처리 결과를 포함해 클라이언트 애플리케이션으로 리다이렉트한다.
        
        클라이언트는 Query String의 'oAuthId'와 'status'를 이용해 인증 결과를 처리해야 합니다.
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
            enum: [ kakao ]
          description: OAuth2 서비스 제공자 이름
        - name: code
          in: query
          required: true
          schema:
            type: string
          description: 인가 코드
      responses:
        302:
          description: OAuth2 인증 성공 후 리다이렉트
          headers:
            Location:
              description: |
                Redirect URL, 인증 성공한 사용자의 'oAuthId'와 'status'를 Query String 값으로 포함
                - oAuthId: OAuth2 서비스 제공자에서 발급한 사용자 식별자(토큰 발급 또는 회원 가입 시 사용)
                - status=new → 신규 사용자
                - status=registered → 기존 회원
              schema:
                type: string
        400:
          description: 잘못된 요청 (지원하지 않는 provider, 인가 코드 누락 등)
        500:
          description: 서버 오류
  /v1/auth/tokens:
    post:
      summary: 토큰 발급 API
      description: |
        인증(또는 등록)된 사용자에게 접근 / 갱신 토큰을 발급할 수 있습니다.
        - OAuth2 인증 성공 후에 발급된 OAuth2 ID를 이용해 토큰을 발급받습니다.
        
        토큰 유효 시간은 다음과 같습니다.
        - 접근 토큰: 2시간
        - 갱신 토큰: 14일
      requestBody:
        $ref: "#/components/requestBodies/TokenIssueRequest"
      responses:
        200:
          $ref: "#/components/responses/OurfitToken"
        400:
          description: |
            요청 본문이 올바른 형식이 아님

            아래와 같은 경우에 발생할 수 있습니다:
            - `oAuthId`가 없거나 공백 문자만 포함됨
        401:
          description: |
            인증 정보를 찾을 수 없음

            아래와 같은 경우에 발생할 수 있습니다:
            - 서버가 `oAuthId`에 해당하는 사용자 정보나 인증 정보를 찾을 수 없음 
            
               → 주로 갱신 토큰까지 만료된 경우에 발생, 다시 OAuth2 로그인을 수행해야 합니다.
            - OAuth2 인증 정보가 만료되어, 갱신을 시도했으나 갱신 토큰도 만료됨(또는 유효하지 않음)
            
               → 다시 OAuth2 로그인을 수행해야 합니다.
            - OAuth2 제공자로부터 인증 실패 응답을 받음 (토큰이 철회되었거나, 계정이 비활성화된 경우)
  /v1/auth/tokens/refresh:
    post:
      summary: 토큰 갱신 API
      description: |
        접근 토큰이 만료된 경우, 유효한 갱신 토큰을 이용해 접근 토큰을 갱신할 수 있습니다.
        
        갱신 토큰의 유효 시간이 1일 미만인 경우, 갱신 토큰도 함께 갱신됩니다.
      requestBody:
        $ref: "#/components/requestBodies/TokenRenewRequest"
      responses:
        200:
          $ref: "#/components/responses/OurfitToken"
        400:
          description: |
            요청 본문이 올바른 형식이 아님

            아래와 같은 경우에 발생할 수 있습니다:
            - `accessToken` 또는 `refreshToken`가 없거나 공백 문자만 포함됨
        401:
          description: |
            인증 정보를 찾을 수 없음
            
            아래와 같은 경우에 발생할 수 있습니다:
            - 접근 토큰이 변조되었거나, 유효한 사용자 정보를 포함하지 않음
            - 갱신 토큰이 만료됨(또는 유효하지 않음)
            
               → 다시 OAuth2 로그인을 수행해야 합니다.
            - 서버의 갱신 토큰과 요청된 갱신 토큰이 일치하지 않음
components:
  requestBodies:
    TokenIssueRequest:
      description: "토큰 발급 요청"
      content:
        application/json:
          schema:
            description: "토큰 발급 요청"
            type: object
            properties:
              oAuthId:
                type: string
                example: "51269223"
                description: "OAuth2 인증 요청 성공 후에 반환된 OAuth2 ID"
    TokenRenewRequest:
      description: "토큰 갱신 요청"
      content:
        application/json:
          schema:
            description: "토큰 갱신 요청"
            type: object
            properties:
              accessToken:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.(truncated)"
                description: "만료된 접근 토큰"
              refreshToken:
                type: string
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.(truncated)"
                description: "유효한 갱신 토큰"
  responses:
    OurfitToken:
      description: "가입 또는 로그인 성공 후, 발급된 JWT 토큰 정보"
      content:
        application/json:
          schema:
            type: object
            properties:
              grantType:
                type: string
                nullable: false
                example: "Bearer"
                description: "토큰 타입(Bearer로 고정)"
              accessToken:
                type: string
                nullable: false
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.(truncated)"
                description: "접근 토큰"
              refreshToken:
                type: string
                nullable: true
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.(truncated)"
                description: "갱신 토큰(토큰 갱신 시에는 nullable)"
              accessTokenExpiresIn:
                type: integer
                nullable: false
                example: 7200
                description: "접근 토큰 만료 시간(초)"
              refreshTokenExpiresIn:
                type: integer
                nullable: true
                example: 604800
                description: "갱신 토큰 만료 시간(초)"
