openapi: 3.0.0
info:
  title: Challenge API
  description: 챌린지 관리 API
  version: 0.0.1
servers:
  - url: https://dev.not-available-yet.com
    description: Development
  - url: https://not-available-yet.com
    description: Production
paths:
  /v1/challenges:
    post:
      summary: 챌린지 생성 API
      security:
        - bearerAuth: [ ]
      requestBody:
        $ref: '#/components/requestBodies/ChallengeCreateRequest'
      responses:
        201:
          description: 챌린지 생성 성공
        400:
          description: |
            요청 본문이 올바른 형식이 아님
            
            아래와 같은 경우에 발생할 수 있습니다:
              - 필수 값이 누락되었거나, ENUM에 정의되지 않은 값이 포함됨
              - 목표 운동 횟수(`goalWorkoutCount`)와 목표 요일 개수(`goalWorkoutDayOfWeeks`)가 일치하지 않음
              - 챌린지 시작일(`startAt`)이 종료일(`endAt`)보다 이후 날짜임
              - 챌린지 기간(`challengeDurationInMonths`)이 시작일과 종료일 간의 개월 수와 맞지 않음
        409:
          description: 이미 등록된 챌린지가 존재함
  /v1/challenges/{challengeId}:
    patch:
      summary: 챌린지 수정 API
      description: |
        챌린지 정보을 수정합니다.
        
        - 챌린지 목표 요일(`goalWorkoutDayOfWeeks`)만 수정할 수 있습니다.
      security:
        - bearerAuth: [ ]
      parameters:
        - name: challengeId
          in: path
          required: true
          example: 52
          description: 수정할 챌린지 ID
      requestBody:
        $ref: '#/components/requestBodies/ChallengeUpdateRequest'
      responses:
        200:
          description: 챌린지 수정 성공
        400:
          description: |
            요청 본문이 올바른 형식이 아님

            아래와 같은 경우에 발생할 수 있습니다:
              - 필수 값이 누락되었거나, ENUM에 정의되지 않은 값이 포함됨
        404:
          description: 챌린지가 존재하지 않음
    delete:
      summary: 챌린지 삭제 API
      security:
        - bearerAuth: [ ]
      parameters:
        - name: challengeId
          in: path
          required: true
          example: 52
          description: 삭제할 챌린지 ID
      responses:
        200:
          description: 챌린지 삭제 성공
  /v1/challenges/me:
    get:
      summary: 내가 현재 진행 중인 챌린지 정보 조회 API
      security:
        - bearerAuth: [ ]
      responses:
        200:
          $ref: '#/components/responses/MyChallengeInfoResponse'
  /v1/challenges/{challengeId}/records:
    post:
      summary: 오늘의 챌린지 도전 완료 처리(오운완) API
      parameters:
        - name: challengeId
          in: path
          required: true
          schema:
            type: number
            example: 5
          description: 챌린지 ID
      security:
        - bearerAuth: [ ]
      requestBody:
        $ref: '#/components/requestBodies/ChallengeRecordAsDoneRequest'
      responses:
        200:
          description: 챌린지 도전 완료 처리 성공
        404:
          description: 챌린지가 존재하지 않음
        409:
          description: |
            리소스가 이 요청을 처리할 수 없는 상태임
            
            - 오늘 도전이 예정되어 있지 않음
            - 이미 오늘의 완료 처리가 되어 있음
  /v1/challenges/{challengeId}/records/{yearMonth}:
    get:
      summary: 챌린지 기록 조회 (월별) API
      security:
        - bearerAuth: [ ]
      parameters:
        - name: challengeId
          in: path
          required: true
          schema:
            type: number
            example: 3
          description: 챌린지 ID
        - name: yearMonth
          in: path
          required: true
          schema:
            type: string
            example: "2025-03"
          description: 조회할 연월(yyyy-MM)
      responses:
        200:
          $ref: '#/components/responses/ChallengeRecordResponse'
        404:
          description: 챌린지가 존재하지 않음
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    ChallengeCreateRequest:
      description: 챌린지 생성 요청
      content:
        application/json:
          schema:
            required:
              - mateId
              - goalWorkoutCount
              - goalWorkoutDayOfWeeks
              - challengeDurationInMonths
              - startAt
              - endAt
            properties:
              mateId:
                type: number
                example: 15
                description: 메이트 ID
              goalWorkoutCount:
                type: number
                example: 3
                description: 목표 운동 횟수
              goalWorkoutDayOfWeeks:
                type: array
                items:
                  type: string
                  enum: [ "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY" ]
                  example: "MONDAY"
                description: 목표 운동 요일
              challengeDurationInMonths:
                type: number
                example: 1
                description: 챌린지 기간(월)
              startAt:
                type: string
                format: date-time
                example: "2025-03-01"
                description: 챌린지 시작일(yyyy-MM-dd)
              endAt:
                type: string
                format: date-time
                example: "2025-04-31"
                description: 챌린지 종료일(yyyy-MM-dd)
    ChallengeUpdateRequest:
      description: 챌린지 수정 요청
      content:
        application/json:
          schema:
            required:
              - goalWorkoutDayOfWeeks
            properties:
              goalWorkoutDayOfWeeks:
                type: array
                items:
                  type: string
                  enum: [ "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY" ]
                  example: "MONDAY"
                  description: 목표 운동 요일
    ChallengeRecordAsDoneRequest:
      description: 오늘의 챌린지 도전 완료 요청
      content:
        application/json:
          schema:
            required:
              - intensityLevel
            properties:
              intensityLevel:
                type: number
                example: "2025-03-13"
                description: |
                  오늘의 운동 강도
                  
                  - 1: 아쉬워요
                  - 2: 적당했어요
                  - 3: 완전 만족해요
  responses:
    ChallengeRecordResponse:
      description: 챌린지 기록 조회 응답
      content:
        application/json:
          schema:
            allOf:
              - $ref: "schemas.yaml#/components/schemas/BaseResponse"
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      properties:
                        id:
                          type: number
                          example: 1
                          description: 챌린지 기록 ID
                        isCompleted:
                          type: boolean
                          example: true
                          description: 챌린지 완료 여부
                        recordDate:
                          type: string
                          format: date-time
                          example: "2025-03-13"
                          description: 완료 또는 예정 날짜(yyyy-MM-dd)
    MyChallengeInfoResponse:
      description: 내 챌린지 조회 응답
      content:
        application/json:
          schema:
            allOf:
              - $ref: "schemas.yaml#/components/schemas/BaseResponse"
              - type: object
                properties:
                  data:
                    type: object
                    properties:
                      challengeId:
                        type: number
                        example: 32
                        description: 챌린지 ID
                      dayElapsed:
                        type: number
                        example: 5
                        description: 챌린지 진행 일수
                      completionRate:
                        type: number
                        example: 10
                        description: 챌린지 완료율(%)
                      remainingDays:
                        type: number
                        example: 35
                        description: 종료까지 남은 일수
                      startAt:
                        type: string
                        format: date-time
                        example: "2025-03-01"
                        description: 챌린지 시작일(yyyy-MM-dd)
                      endAt:
                        type: string
                        format: date-time
                        example: "2025-03-31"
                        description: 챌린지 종료일(yyyy-MM-dd)