openapi: 3.0.0
info:
  title: Workout API
  description: 운동 종류 관리 API
  version: 0.0.1
servers:
  - url: https://api.ourfit.life
paths:
  /v1/workout-types:
    get:
      summary: 운동 종류 목록 조회
      description: 등록된 운동 종류 목록 전체를 조회합니다.
      security:
        - bearerAuth: [ ]
      responses:
        200:
          $ref: "#/components/responses/WorkoutListResponse"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    WorkoutListResponse:
      description: 운동 종류 목록 조회 응답
      content:
        application/json:
          schema:
            allOf:
              - $ref: "schemas.yaml#/components/schemas/BaseResponse"
              - type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/WorkoutResponse"
  schemas:
    WorkoutResponse:
      type: object
      properties:
        code:
          type: string
          example: "PILATES"
          description: 운동 코드
        name:
          type: string
          example: "필라테스"
          description: 운동 이름